# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    active: false
  NoWildcardImports:
    active: false
  MaximumLineLength:
    maxLineLength: 150

style:
  ReturnCount:
    active: false
  WildcardImport:
    active: false
  ThrowsCount:
    max: 3
